ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER community_oyj IDENTIFIED BY community1234;

ALTER USER community_oyj DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CONNECT, RESOURCE, CREATE VIEW TO community_oyj;